file = open("MapArray.txt","r")
superString = file.read()
superArr = superString.split(",")

for y in range(50):
    tempString = ""
    for x in range(80):
        num = int(superArr[x + y*80])
        char = ""
        if(num == 0):
            char = ','
        if(num == 1):
            char = '─'
        if(num == 2):
            char = '│'
        if(num == 3):
            char = '#'
        if(num == 4):
            char = 'O'
        if(num == 5):
            char = '└'
        if(num == 6):
            char = '┘'
        if(num == 7):
            char = '┌'
        if(num == 8):
            char = '┐'
        if(num == 9):
            char = '├'
        if(num == 10):
            char = '┤'
        if(num == 11):
            char = '┴'
        if(num == 12):
            char = '┬'
        if(num == 13):
            char = '┼'
        if(num == 14):
            char = '░'
        if(num == 20):
            char = '▲'
        if(num == 21):
            char = '▼'
        if(num == 22):
            char = '◍'
        if(num == 23):
            char = '◊'
        tempString += char
    print(tempString)

"""
if(num == 0):
            char = ','
        if(num == 1):
            char = '─'
        if(num == 2):
            char = '│'
        if(num == 3):
            char = '#'
        if(num == 4):
            char = 'O'
        if(num == 5):
            char = '└'
        if(num == 6):
            char = '┘'
        if(num == 7):
            char = '┌'
        if(num == 8):
            char = '┐'
        if(num == 9):
            char = '├'
        if(num == 10):
            char = '┤'
        if(num == 11):
            char = '┴'
        if(num == 12):
            char = '┬'
        if(num == 13):
            char = '┼'
        if(num == 14):
            char = '░'
        if(num == 20):
            char = '▲'
        if(num == 21):
            char = '▼'
        if(num == 22):
            char = '◍'
        if(num == 23):
            char = '◊'
        """
